const header=document.querySelector('.header'),menu=document.querySelector('.menu'),nav=document.querySelector('#nav');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open);document.body.classList.toggle('nav-open',!open)});
document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('open');document.body.classList.remove('nav-open')}));addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>25),{passive:true});
const dialog=document.querySelector('#lightbox'),dialogImage=dialog.querySelector('img'),dialogCaption=dialog.querySelector('p');let lastFocus;document.querySelectorAll('.gallery-item[data-src]').forEach(item=>item.addEventListener('click',()=>{lastFocus=item;dialogImage.src=item.dataset.src;dialogImage.alt=item.querySelector('img').alt;dialogCaption.textContent=item.dataset.caption;dialog.showModal()}));dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>lastFocus?.focus());document.querySelector('.gallery-item.texture').addEventListener('click',()=>document.querySelector('#quote').scrollIntoView());
const form=document.querySelector('#quote-form'),steps=[...form.querySelectorAll('.step')],dots=[...form.querySelectorAll('.progress span')],next=form.querySelector('.next'),back=form.querySelector('.back'),submit=form.querySelector('.submit'),error=form.querySelector('.form-error');let current=0;
function showStep(){steps.forEach((s,i)=>s.classList.toggle('active',i===current));dots.forEach((d,i)=>{d.classList.toggle('active',i===current);d.classList.toggle('done',i<current)});back.hidden=current===0;next.hidden=current===steps.length-1;submit.hidden=current!==steps.length-1;error.textContent=''}
function validStep(){const fields=[...steps[current].querySelectorAll('input[required],textarea[required]')];const radioNames=[...new Set(fields.filter(f=>f.type==='radio').map(f=>f.name))];const invalid=fields.find(f=>f.type!=='radio'&&!f.checkValidity())||radioNames.find(n=>!form.querySelector(`input[name="${n}"]:checked`));if(invalid){error.textContent='Please complete this step before continuing.';if(invalid instanceof HTMLElement)invalid.reportValidity?.();return false}return true}
next.addEventListener('click',()=>{if(validStep()){current++;showStep();form.scrollIntoView({behavior:'smooth',block:'center'})}});back.addEventListener('click',()=>{current--;showStep()});
const input=document.querySelector('#photos'),previews=document.querySelector('#previews'),drop=document.querySelector('.drop');function previewFiles(files){previews.replaceChildren();[...files].slice(0,6).forEach(file=>{if(!file.type.startsWith('image/'))return;const img=document.createElement('img');img.src=URL.createObjectURL(file);img.alt=`Selected image: ${file.name}`;img.onload=()=>URL.revokeObjectURL(img.src);previews.append(img)})}input.addEventListener('change',()=>previewFiles(input.files));['dragenter','dragover'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>{input.files=e.dataTransfer.files;previewFiles(input.files)});
form.addEventListener('submit',e=>{e.preventDefault();if(!validStep())return;const success=form.querySelector('.success');success.querySelector('b').textContent=form.elements.name.value.trim();form.querySelectorAll(':scope > :not(.success)').forEach(el=>el.hidden=true);success.classList.add('show');success.focus()});showStep();
